language: node_js

node_js:
  - "7.2"
  - "6.9"
  - "5.12"
  - "4.6"

services:
  - mysql

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_PORT= MYSQL_USER=root MYSQL_PASSWORD= MYSQL_DB=adelia_test

before_script:
  - mysql < schemas/adelia_test.sql

script: npm run test-ci
