language: node_js

node_js:
  - "7.3"
  - "6.9"
  - "5.12"
  - "4.7"

services:
  - mysql

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_PORT= MYSQL_USER=root MYSQL_PASSWORD= MYSQL_DB=adelia_test
  # - DB=sqlite SQLITE_DB=./db/sqlite/adelia_test.sqlite MYSQL_HOST=127.0.0.1 MYSQL_PORT= MYSQL_USER=root MYSQL_PASSWORD= MYSQL_DB=adelia_test

before_script:
  - mysql < schemas/mysql/adelia_test.sql

script: npm run test-ci
