'use strict';

const _ = require('lodash'),
  Promise = require('bluebird'),
  mysql = require('mysql'),
  sprintf = require('sprintf-js').sprintf;

const DEBUG = process.env.DEBUG;

// TODO: move to initialization
// e.g.:
//   const adelia = require('adelia')(CONFIG);
//   const model = new adelia.Model();
const CONFIG = {
  host: process.env.MYSQL_HOST,
  port: process.env.MYSQL_PORT,
  user: process.env.MYSQL_USER,
  password: process.env.MYSQL_PASSWORD,
  database: process.env.MYSQL_DB
};

function MySQLAdapter() {
}

_.assign(MySQLAdapter.prototype, {
  /**
   *  @attr NAME
   *  @short Name of this adapter
   */
  NAME: 'mysql',

  /**
   *  @attr queries_count
   *  @short Counter for queries executed.
   */
  queries_count: 0,

  /**
   *  @attr connection
   *  @short Connection link to the database.
   */
  connection: null,

  /**
   *  @attr query
   *  @short Query for the database.
   */
  query: null,

  /**
   *  @attr result
   *  @short The result of the last query.
   */
  result: null,

  /**
   *  @fn connect
   *  @short Connects to the database.
   */
  connect: function() {
    if (_.isUndefined(this.connection) || this.connection === null) {
      this.connection = mysql.createConnection(CONFIG);
      this.connection.connect();
    }
    return Promise.resolve(this.connection);
  },

  /**
   *  @fn select_db(database_name)
   *  @short Selects the desired database.
   *  @param database_name The name of the database.
   */
  // select_db: function(database_name) {
  //   this.connect();
  //   return mysql_select_db(database_name, this.link);
  // },

  /**
   *  @fn close
   *  @short Closes the connection to the database.
   */
  close: function() {
    this.connection.end();
  },

  /**
   *  @fn prepare(query)
   *  @short Prepares a query for execution
   *  @param query The query to execute.
   */
  prepare: function(query) {
    const self = this;
    const args = arguments;
    const args_len = arguments.length;

    return this.connect()
      .then(function() {
        if (args_len > 1) {
          for (let i = 1; i < args_len; i++) {
            // query = query.replace('{' + i + '}', mysql.escape(args[i]));
            query = query.replace('{' + i + '}', args[i]);
          }
        }
        self.query = query;

        if (DEBUG) {
          self._printQuery();
        }

        return query;
      });
  },

  /**
   *  @fn exec
   *  @short Executes a query.
   */
  exec: function() {
    const self = this;

    return this.connect()
      .then(function() {
        let res, rej;

        const promise = new Promise(function(resolve, reject) {
          res = resolve;
          rej = reject;
        });
        self.result = self.connection.query(self.query, function(err, results) {
          if (err) {
            rej(err);
            return;
          }
          res(results);
        });
        self.queries_count++;

        return promise;
      });
  },

  /**
   *  @fn deleteOne
   *  @short Deletes one row
   *  @param tableName Name of table
   *  @param keyColumn Name of key column
   *  @param keyValue Value of key column
   *  @param options Misc options
   */
  deleteOne: function(tableName, keyColumn, keyValue, options) {
    return this.delete(tableName, keyColumn, keyValue, _.merge(options, {
      one: true
    }));
  },

  /**
   *  @fn delete
   *  @short Deletes rows
   *  @param tableName Name of table
   *  @param keyColumn Name of key column
   *  @param keyValue Value of key column
   *  @param options Misc options
   */
  delete: function(tableName, keyColumn, keyValue, options) {
    const self = this;

    return this.connect()
      .then(function() {
        return self.prepare(sprintf("DELETE FROM `{1}` WHERE `%s` = '{2}'%s",
          keyColumn, options.one ? ' LIMIT 1' : ''),
            tableName, keyValue);
      })
      .then(function() {
        return self.exec();
      })
      .then(function() {
        if (options.optimize) {
          return self.prepare('OPTIMIZE TABLE `{1}`', tableName)
            .then(function() {
              return self.exec();
            });
        }
      });
  },

  /**
   *  @fn getColumns
   *  @short Describes a table.
   */
  getColumns: function(tableName) {
    const self = this;

    return this.connect()
      .then(function() {
        return self.prepare('DESCRIBE `{1}`', tableName);
      })
      .then(function() {
        return self.exec();
      })
      .then(function(results) {
        return _.map(results, function(row) {
          return row['Field'];
        });
      });
  },

  /**
   *  @fn insert_id
   *  @short Returns the id generated by the last INSERT query.
   */
  insert_id: function() {
    return mysql_insert_id(this.link);
  },

  /**
   *  @fn escape(value)
   *  @short Escapes the given value to avoid SQL injections.
   *  @param value The value to escape.
   */
  escape: function(value) {
    this.connect();
    return mysql.escape(value, this.link);
  },


  /**
   *  @fn result(pos, colname)
   *  @short Returns a single result of the last SELECT query.
   *  @param row The row of the resultset.
   *  @param colname The name (or the alias, if applicable) of the desired row.
   */
  result: function(pos, colname) {
    pos = pos || 0;

    if (colname === undefined) {
      colname = null;
    }

    return mysql_result(this.result, pos, colname);
  },

  /**
   *  @fn num_rows
   *  @short Returns the number of rows returned by a previous SELECT query.
   */
  num_rows: function() {
    return mysql_num_rows(this.result);
  },

  /**
   *  @fn affected_rows
   *  @short Returns the number of rows affected by a previous INSERT, UPDATE or DELETE query.
   */
  affected_rows: function() {
    return mysql_affected_rows(this.result);
  },

  /**
   *  @fn fetch_assoc
   *  @short Returns the current row of the resultset as an associative array.
   */
  fetch_assoc: function() {
    return mysql_fetch_assoc(this.result);
  },

  /**
   *  @fn fetch_array
   *  @short Returns the current row of the resultset as an array.
   */
  fetch_array: function() {
    return mysql_fetch_array(this.result);
  },

  /**
   *  @fn free_result
   *  @short Releases the result of the last query.
   */
  free_result: function() {
    mysql_free_result(this.result);
  },

  /**
   *  @fn _printQuery
   *  @short Prints the query to the console.
   */
  _printQuery: function() {
    console.log(this.query);
  }
});

module.exports = MySQLAdapter;
